# Apply to all files without commiting:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate

exclude: ^(here/you/can/exclude/a/folder/)

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-ast
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-docstring-first
        exclude: ^(here/you/can/exclude/a/folder/|and/a/second/one/)
    -   id: check-executables-have-shebangs
        exclude: ^(here/you/can/exclude/a/file)
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-aws-credentials
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==23.1.0]
-   repo: local
    hooks:
    -   id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        stages: [commit]
        files: \.ipynb$
        language: system
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
#-   repo: https://github.com/PyCQA/flake8
#    rev: '6.0.0'
#    hooks:
#    -   id: flake8
#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.790
#    hooks:
#    -   id: mypy
#        args: [--ignore-missing-imports]
