name: balluff
channels:
  - conda-forge
  # We want to have a reproducible setup, so we don't want default channels,
  # which may be different for different users. All required channels should
  # be listed explicitly here.
dependencies:
  - python~=3.8
  - poetry~=1.5
  - conda-lock
  - mamba
  - pip  # pip must be mentioned explicitly, or conda-lock will fail

platforms:
  - linux-64
  - osx-64
  - win-64
